// See https://aka.ms/new-console-template for more information

using Orders.State.Pattern.App.DocumentModel;

Console.WriteLine("-------------------------------------------------------------");
Console.WriteLine("         DOCUMENTO 1 CON DOS LINEAS DE FACTURA");
Console.WriteLine("-------------------------------------------------------------");
var header = Header.Create(2024,"Golosinas CarlosV");
var document = Document.Create(header);
var line = Line.Create(document.Number, header.Exercise, 1, "CV", 23.25);
document.RegisterLine(line);
var line2 = Line.Create(document.Number, header.Exercise, 2, "CV", 13.28);
document.RegisterLine(line2);

Console.Write("El ESTADO INICIAL del documento es ");
Console.ForegroundColor = ConsoleColor.DarkMagenta;
Console.WriteLine(document.GetState());
Console.ForegroundColor = ConsoleColor.White;
Console.Write("El TIPO INICIAL del documento es ");
Console.ForegroundColor = ConsoleColor.DarkMagenta;
Console.WriteLine(document.Type);
Console.ForegroundColor = ConsoleColor.White;
Console.ForegroundColor = ConsoleColor.DarkGreen;
Console.WriteLine();
Console.WriteLine("PROCESAMOS DOCUMENTO");
Console.WriteLine();
Console.ForegroundColor = ConsoleColor.White;
document.Process();
Console.Write("El ESTADO del documento es ");
Console.ForegroundColor = ConsoleColor.DarkMagenta;
Console.WriteLine(document.GetState());
Console.ForegroundColor = ConsoleColor.White;
Console.Write("El TIPO del documento es ");
Console.ForegroundColor = ConsoleColor.DarkMagenta;
Console.WriteLine(document.Type);
Console.ForegroundColor = ConsoleColor.White;
Console.ForegroundColor = ConsoleColor.DarkGreen;
Console.WriteLine();
Console.WriteLine("PROCESAMOS DOCUMENTO");
Console.WriteLine();
Console.ForegroundColor = ConsoleColor.White;
document.Process();
Console.Write("El ESTADO del documento es ");
Console.ForegroundColor = ConsoleColor.DarkMagenta;
Console.WriteLine(document.GetState());
Console.ForegroundColor = ConsoleColor.White;

Console.WriteLine();
Console.WriteLine("-------------------------------------------------------------");
Console.WriteLine("         DOCUMENTO 2 CON UNA LINEA DE FACTURA");
Console.WriteLine("-------------------------------------------------------------");
header = Header.Create(2024, "Golosinas CarlosV");
document = Document.Create(header);
line = Line.Create(document.Number, header.Exercise, 1, "CV", 239.69);
document.RegisterLine(line);

Console.Write("El ESTADO INICIAL del documento es ");
Console.ForegroundColor = ConsoleColor.DarkMagenta;
Console.WriteLine(document.GetState());
Console.ForegroundColor = ConsoleColor.White;
Console.Write("El TIPO INICIAL del documento es ");
Console.ForegroundColor = ConsoleColor.DarkMagenta;
Console.WriteLine(document.Type);
Console.ForegroundColor = ConsoleColor.White;
Console.ForegroundColor = ConsoleColor.DarkGreen;
Console.WriteLine();
Console.WriteLine("PROCESAMOS DOCUMENTO");
Console.WriteLine();
Console.ForegroundColor = ConsoleColor.White;
document.Process();
Console.Write("El ESTADO del documento es ");
Console.ForegroundColor = ConsoleColor.DarkMagenta;
Console.WriteLine(document.GetState());
Console.ForegroundColor = ConsoleColor.White;
Console.Write("El TIPO del documento es ");
Console.ForegroundColor = ConsoleColor.DarkMagenta;
Console.WriteLine(document.Type);
Console.ForegroundColor = ConsoleColor.White;
Console.ForegroundColor = ConsoleColor.DarkGreen;
Console.WriteLine();
Console.WriteLine("PROCESAMOS DOCUMENTO");
Console.WriteLine();
Console.ForegroundColor = ConsoleColor.White;
document.Process();
Console.Write("El ESTADO del documento es ");
Console.ForegroundColor = ConsoleColor.DarkMagenta;
Console.WriteLine(document.GetState());
Console.ForegroundColor = ConsoleColor.White;


Console.ReadLine();